### ISSUE TITLE
Target `qrcodegencpp::qrcodegencpp` does not seem to work

### ISSUE THREAD

**Issue by tytan652** [EasyCoding/qrcodegen-cmake#19]
### Problem details

Continuation of what said in https://github.com/obsproject/obs-deps/pull/182.

The target `qrcodegencpp::qrcodegencpp` does not seem to work unlike `qrcodegencpp` that does work.

### Steps to reproduce

1. Install qrcodegencpp with this CMake "patch"
2. Apply the patch https://src.fedoraproject.org/rpms/obs-studio/blob/rawhide/f/obs-studio-websocket-use-system-qrcodegencpp.patch to a clone of obs-studio repo
3. Replace `qrcodegencpp` by `qrcodegencpp::qrcodegencpp` in the `target_link_libraries()` of obs-websocket `legacy.cmake` file (we are progressively rewriting our CMake per OS/Platform so it might be weird for you)
4. The project will error while configuring

### Expected behavior

No configuration error, `qrcodegencpp::qrcodegencpp` must have worked.

### Actual behavior

The target `qrcodegencpp::qrcodegencpp` is not found.

### Project version

1.8.0

### OS name and version

Arch Linux (with qrcodegen-cmake AUR package)

### C/C++ compiler

GCC

### Compiler version

12.2.1

### CMake version

3.26.3

### Logs

```text
-- Configuring done (2.7s)
CMake Error at plugins/obs-websocket/cmake/legacy.cmake:131 (target_link_libraries):
  Target "obs-websocket" links to:

    qrcodegencpp::qrcodegencpp

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  cmake/Modules/ObsHelpers.cmake:519 (include)
  plugins/obs-websocket/CMakeLists.txt:3 (legacy_check)


-- Generating done (0.1s)
CMake Generate step failed.  Build files cannot be regenerated correctly.
*** Failure: Exit code 1 ***
```

**Comment by xvitaly** [comment]
Can you post generated `qrcodegen-cpp-targets*.cmake` files?

**Comment by tytan652** [comment]
```cmake
#----------------------------------------------------------------
# Generated CMake target import file for configuration "Release".
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Import target "qrcodegencpp::qrcodegencpp" for configuration "Release"
set_property(TARGET qrcodegencpp::qrcodegencpp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(qrcodegencpp::qrcodegencpp PROPERTIES
  IMPORTED_LOCATION_RELEASE "${_IMPORT_PREFIX}/lib/libqrcodegencpp.so.1.8.0"
  IMPORTED_SONAME_RELEASE "libqrcodegencpp.so.1"
  )

list(APPEND _cmake_import_check_targets qrcodegencpp::qrcodegencpp )
list(APPEND _cmake_import_check_files_for_qrcodegencpp::qrcodegencpp "${_IMPORT_PREFIX}/lib/libqrcodegencpp.so.1.8.0" )

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
```

**Comment by xvitaly** [comment]
`qrcodegencpp::qrcodegencpp` target exists. It's very strange.

**Comment by xvitaly** [comment]
I was able to reproduce.

**Comment by tytan652** [comment]
The target `qrcodegencpp::qrcodegencpp` now works with master.

**Comment by xvitaly** [comment]
> The target qrcodegencpp::qrcodegencpp now works with master.

Great. Thanks for the report and testing. Tagged as [v1.8.0-cmake2](https://github.com/EasyCoding/qrcodegen-cmake/releases/tag/v1.8.0-cmake2).
